export const AUTHENTICATE_PENDING = 'AUTHENTICATE_PENDING';
export const AUTHENTICATE_FULFILLED = 'AUTHENTICATE_FULFILLED';
export const AUTHENTICATE_REJECTED = 'AUTHENTICATE_REJECTED';
export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_FULFILLED = 'REGISTER_FULFILLED';
export const REGISTER_REJECTED = 'REGISTER_REJECTED';
